"project_id": "CROWDIN_PROJECT_ID"
"api_token": "CROWDIN_PERSONAL_TOKEN"
"preserve_hierarchy": true

files:
  - source: "/src/i18n/en/**/*"
  - translation: "/src/i18n/%two_letters_code%/**/%original_file_name%"